language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"

# command to install dependencies
install: pip install pipenv; pipenv lock; pipenv install --dev

# command to run tests
script: pipenv run pytest tests/
